language: android

android:
  components:
    - platform-tools
    - tools

branches:
  only:
    - master

before_install:
    - chmod +x gradlew
    - git config --global user.email "ci@donmatheo.de"
    - git config --global user.name "Travis CI"

script: ./gradlew html:dist
