language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.0.0
    - android-21

branches:
  only:
    - master

before_install:
    - chmod +x gradlew
    - git config --global user.email "ci@donmatheo.de"
    - git config --global user.name "Travis CI"
    - git config --global push.default simple

script: ./gradlew build

after_success:
    - mkdir ../pages
    - cd ../pages
    - git clone -b gh-pages --single-branch https://github.com/donmatheo/unstable-relations.git gh-pages
    - mv gh-pages/latest_build gh-pages/archive/build_$((TRAVIS_JOB_ID - 2))
    - cp -r ../unstable-relations/html/build/dist gh-pages/latest_build
    - cp -r ../core/build/reports/tests/ gh-pages/tests
    - cd gh-pages
    - echo "$((TRAVIS_JOB_ID - 1))" >> latest_build/version.txt
    - git add tests
    - git add latest_build
    - git add archive
    - git commit -a -m "Committed by Travis-CI (build number - $((TRAVIS_JOB_ID - 1)))"
    - git push -q https://$token@github.com/donmatheo/unstable-relations.git HEAD:gh-pages