language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.0.0
    - android-21

branches:
  only:
    - box2dlights

before_install:
    - chmod +x gradlew
    - git config --global user.email "ci@donmatheo.de"
    - git config --global user.name "Travis CI"
    - git config --global push.default simple

script:
    - ./gradlew html:dist

after_failure:
    - cd ..
    - git clone -b gh-pages --single-branch https://github.com/donmatheo/unstable-relations.git gh-pages
    - cd gh-pages
    - cp -r ../unstable-relations/core/build/reports/tests/ tests
    - git add tests

after_success:
    - cd ..
    - git clone -b gh-pages --single-branch https://github.com/donmatheo/unstable-relations.git gh-pages
    - cd gh-pages
    - mv box2dlights archive/box2dlights_$((TRAVIS_JOB_ID - 2))
    - cp -r ../unstable-relations/html/build/dist/ box2dlights
    - echo "$((TRAVIS_JOB_ID - 1))" >> box2dlights/version.txt
    - git add box2dlights
    - git add archive

after_script:
    - git commit -a -m "Committed by Travis-CI (build number - $((TRAVIS_JOB_ID - 1)))"
    - git pull
    - git push -q https://$token@github.com/donmatheo/unstable-relations.git HEAD:gh-pages
