language: android

android:
  components:
    - platform-tools
    - tools

branches:
  only:
    - master

before_install:
    - chmod +x gradlew
    - git config --global user.email "ci@donmatheo.de"
    - git config --global user.name "Travis CI"
    - git config --global push.default simple

script: ./gradlew html:dist

after_script:
    - mkdir ../pages
    - cd ../pages
    - git clone -b gh-pages --single-branch https://github.com/donmatheo/unstable-relations.git gh-pages
    - mv gh-pages/app gh-pages/app_$((TRAVIS_JOB_ID - 2))
    - cp -r ../unstable-relations/html/build/dist gh-pages/app
    - cd gh-pages
    - echo "$((TRAVIS_JOB_ID - 1))" >> gh-pages/app/version.txt
    - git add app
    - git add app_$((TRAVIS_JOB_ID - 2))
    - git commit -a -m "Committed by Travis-CI (build number - $((TRAVIS_JOB_ID - 1)))"
    - git push -q https://$token@github.com/donmatheo/unstable-relations.git HEAD:gh-pages