language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.0.0
    - android-21

before_install:
    - chmod +x gradlew
    - git config --global user.email "ci@donmatheo.de"
    - git config --global user.name "Travis CI"
    - git config --global push.default simple

script:
    - ./gradlew html:dist --stacktrace
    - ./gradlew android:assembleRelease
    - ./gradlew desktop:dist


after_failure:
    - cd ..
    - git clone -b gh-pages --single-branch https://github.com/donmatheo/unstable-relations.git gh-pages
    - cd gh-pages
    - cp -r ../unstable-relations/core/build/reports/tests/ tests
    - git add tests

after_success:
    - cd ..
    - git clone -b gh-pages --single-branch https://github.com/donmatheo/unstable-relations.git gh-pages
    - cd gh-pages
    - mv $TRAVIS_BRANCH archive/$((TRAVIS_BUILD_NUMBER - 1))
    - cp -r ../unstable-relations/html/build/dist/ $TRAVIS_BRANCH
    - echo "$((TRAVIS_BUILD_NUMBER))" >> $TRAVIS_BRANCH/version.txt
    - cp -r ../unstable-relations/desktop/build/libs/ release/
    - cp -r ../unstable-relations/android/build/outputs/apk/android-release-unsigned.apk release/magical-dots-unsigned.apk
    - git add $TRAVIS_BRANCH
    - git add archive

after_script:
    - git commit -a -m "Committed by Travis-CI (build number - $((TRAVIS_BUILD_NUMBER)))"
    - git pull
    - git push -q https://$token@github.com/donmatheo/unstable-relations.git HEAD:gh-pages
