language: java

jdk:
 - oraclejdk7

branches:
  only:
    - master

before_script:
 - chmod +x grailsw

deploy:
  provider: gae
  oauth_refresh_token: deadbeef0123456789
  skip_cleanup: true
  app_dir: foo # defaults to $TRAVIS_BUILD_DIR

notifications:
    recipients:
      - games@donmatheo.de
    email:
      on_success: change
      on_failure: always