language: android

android:
  components:
    - platform-tools
    - tools

branches:
  only:
    - master

before_install:
    - echo $JAVA_HOME
    - chmod +x gradlew




script: ./gradlew html:dist --stacktrace

deploy:
  provider: gae
  oauth_refresh_token: deadbeef0123456789
  skip_cleanup: true
  app_dir: foo # defaults to $TRAVIS_BUILD_DIR
  edge: true