language: android

android:
  components:
    - platform-tools
    - tools
    - oraclejdk7

branches:
  only:
    - master

before_install:
- chmod +x gradlew

before_script:
   - wget http://google-web-toolkit.googlecode.com/files/gwt-2.5.1.zip -O /tmp/gwt-2.5.1.zip
   - unzip -qq /tmp/gwt-2.5.1.zip
   - export GWT_HOME=$PWD/gwt-2.5.1/
   - export PATH=$PATH:$GWT_HOME

script: ./gradlew html:dist

deploy:
  provider: gae
  oauth_refresh_token: deadbeef0123456789
  skip_cleanup: true
  app_dir: foo # defaults to $TRAVIS_BUILD_DIR
  edge: true