language: android

android:
  components:
    - platform-tools
    - tools

branches:
  only:
    - master

before_install:
    - chmod +x gradlew

script: ./gradlew html:dist

before_deploy:
    - mkdir ../pages
    - cd ../pages
    - git clone -b gh-pages --single-branch https://github.com/donmatheo/unstable-relations.git gh-pages
    - cd gh-pages

deploy:
    - cp ../../unstable-relations/html/dist app/
    - git add app
    
